// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqq-pNjl2ToM4iQvDezdgeZh2ji2VK9_8',
    appId: '1:943737878340:android:82acc42539b61aab798911',
    messagingSenderId: '943737878340',
    projectId: 'flutter-course-206de',
    databaseURL: 'https://flutter-course-206de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-course-206de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMr5Yidny8DWxMsvKVWsSb4aNrNzkeoqY',
    appId: '1:943737878340:ios:5fb08a1fdf2b4397798911',
    messagingSenderId: '943737878340',
    projectId: 'flutter-course-206de',
    databaseURL: 'https://flutter-course-206de-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-course-206de.appspot.com',
    iosClientId: '943737878340-d077ugmlcdmhg2g4v0hhfqr93bf5kllu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
